INSERT INTO public.team (id, department_id, label) VALUES (1, 1, 'Norms');
INSERT INTO public.team (id, department_id, label) VALUES (2, 1, 'Productivity');
INSERT INTO public.team (id, department_id, label) VALUES (3, 1, 'Safety');
INSERT INTO public.team (id, department_id, label) VALUES (4, 2, 'Data analysis');
INSERT INTO public.team (id, department_id, label) VALUES (5, 2, 'Previsions');
INSERT INTO public.team (id, department_id, label) VALUES (6, 2, 'Innovation');
INSERT INTO public.team (id, department_id, label) VALUES (7, 3, 'Prospection');
INSERT INTO public.team (id, department_id, label) VALUES (8, 3, 'Relations');
INSERT INTO public.team (id, department_id, label) VALUES (9, 4, 'Digital');
INSERT INTO public.team (id, department_id, label) VALUES (10, 4, 'Social Networks');
INSERT INTO public.team (id, department_id, label) VALUES (11, 5, 'Recruitment');
INSERT INTO public.team (id, department_id, label) VALUES (12, 5, 'HR Management');
INSERT INTO public.team (id, department_id, label) VALUES (13, 6, 'Accounting');
INSERT INTO public.team (id, department_id, label) VALUES (14, 6, 'Finance');
INSERT INTO public.team (id, department_id, label) VALUES (15, 7, 'Prospection');
INSERT INTO public.team (id, department_id, label) VALUES (16, 7, 'KAM');
INSERT INTO public.team (id, department_id, label) VALUES (17, 8, 'CS Web');
INSERT INTO public.team (id, department_id, label) VALUES (18, 8, 'CS Phone');
INSERT INTO public.team (id, department_id, label) VALUES (19, 9, 'Maintenance');
INSERT INTO public.team (id, department_id, label) VALUES (20, 9, 'Development');