INSERT INTO public.team (id, label, department_id) VALUES (1, 'Norms', 1);
INSERT INTO public.team (id, label, department_id) VALUES (2, 'Productivity', 1);
INSERT INTO public.team (id, label, department_id) VALUES (3, 'Safety', 1);
INSERT INTO public.team (id, label, department_id) VALUES (4, 'Data analysis', 2);
INSERT INTO public.team (id, label, department_id) VALUES (5, 'Previsions', 2);
INSERT INTO public.team (id, label, department_id) VALUES (6, 'Innovation', 2);
INSERT INTO public.team (id, label, department_id) VALUES (7, 'Prospection', 3);
INSERT INTO public.team (id, label, department_id) VALUES (8, 'Relations', 3);
INSERT INTO public.team (id, label, department_id) VALUES (9, 'Digital', 4);
INSERT INTO public.team (id, label, department_id) VALUES (10, 'Social Networks', 4);
INSERT INTO public.team (id, label, department_id) VALUES (11, 'Recruitment', 5);
INSERT INTO public.team (id, label, department_id) VALUES (12, 'HR Management', 5);
INSERT INTO public.team (id, label, department_id) VALUES (13, 'Accounting', 6);
INSERT INTO public.team (id, label, department_id) VALUES (14, 'Finance', 6);
INSERT INTO public.team (id, label, department_id) VALUES (15, 'Prospection', 7);
INSERT INTO public.team (id, label, department_id) VALUES (16, 'KAM', 7);
INSERT INTO public.team (id, label, department_id) VALUES (17, 'CS Web', 8);
INSERT INTO public.team (id, label, department_id) VALUES (18, 'CS Phone', 8);
INSERT INTO public.team (id, label, department_id) VALUES (19, 'Maintenance', 9);
INSERT INTO public.team (id, label, department_id) VALUES (20, 'Development', 9);